name: Nest CI Workflow

on:
  push:
    branches:
      - daily_task

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Node Setup Completed
        run: echo 'Node Js Working Successfull'

      - name: Run tests
        run: echo 'Unit Test Executed Successfully'

      - name: Complete Job
        run: echo 'All Process Completed'